// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG0ptK5hRO75a8MTuTTeXQGHLIqn4ltwo',
    appId: '1:16499338794:web:057d45e063092825e6dd53',
    messagingSenderId: '16499338794',
    projectId: 'h-flix',
    authDomain: 'h-flix.firebaseapp.com',
    storageBucket: 'h-flix.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_CeXkSvA3Oks00TWofaNJHhMAFmO_I5E',
    appId: '1:16499338794:android:f703d327d83a50e5e6dd53',
    messagingSenderId: '16499338794',
    projectId: 'h-flix',
    storageBucket: 'h-flix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwO8oC8r7GfnAQb7Fr_3yf0jmJk5zb_dY',
    appId: '1:16499338794:ios:b9263d1cabde38fae6dd53',
    messagingSenderId: '16499338794',
    projectId: 'h-flix',
    storageBucket: 'h-flix.appspot.com',
    iosClientId:
        '16499338794-9o7si8733q1636mv5t4do1j6civ0htc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwO8oC8r7GfnAQb7Fr_3yf0jmJk5zb_dY',
    appId: '1:16499338794:ios:42ef2d7c61cbda18e6dd53',
    messagingSenderId: '16499338794',
    projectId: 'h-flix',
    storageBucket: 'h-flix.appspot.com',
    iosClientId:
        '16499338794-1nfh9jmeaddcj005ujf7firnnk0a7uej.apps.googleusercontent.com',
    iosBundleId: 'com.example.front.RunnerTests',
  );
}
